Sprint 1
zayarnaya/middle.messenger.praktikum.yandex pull request #1
Opened 2022-07-24 07:28 UTC by zayarnaya

Задание первого спринта для проверки.

2022-07-24 12:03 UTC, podlovchenko requested changes
Привет) Есть несколько замечаний:
1. Проект локально запускается не на 3000 порту
2. Нет команды для запуска сервера
3. Верстка сильно не соответствует макетам
4. Контент везде добавлен в элемент через innerHTML . Необходимо стараться использовать textContent
5. Поехало форматирование кода (отступы, разделение строками, написание операторов), прикладываю [ссылку](https://learn.javascript.ru/coding-style) на общепринятые правила по код стайлу, также можно использовать [prettier](https://prettier.io/docs/en/install.html)
6. Также стоит почитать о том, в каких случаях использовать let, в каких const 

Жду доработок)

2022-07-24 12:03 UTC, podlovchenko commented on package.json
> +    "express": "^4.18.1",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-07-24 12:03 UTC, podlovchenko commented on src/components/avatars/change-avatar/change-avatar.hbs
> +</div>
Для лучше читабельности стоит соблюдать отступы

2022-07-24 12:03 UTC, podlovchenko commented on src/components/avatars/profile_avatar/profile-avatar.hbs
> +        </div>
Во многих файлах ошибка EOF
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-07-24 12:03 UTC, podlovchenko commented on package.json
> +    "build": "parcel build src/index.html"
Нет команды для запуска server.js

2022-07-24 12:03 UTC, podlovchenko commented on package.json
> +    "dev": "parcel src/index.html",
Эта команда запускает приложение не на 3000 порту, нужно добавить флаг --port

2022-07-24 12:03 UTC, podlovchenko commented on src/components/buttons/button-submit/button-submit.js
> +let template = "Handlebars <b>{{doesWhat}}</b> precompiled!";
Если переменная не изменяется, то следуют ее объявить через const

2022-07-24 12:03 UTC, podlovchenko commented on src/components/buttons/button-submit/button-submit.js
> +let Handlebars = require("handlebars");
Импорт из библиотек идет обычно вначале файла

2022-07-24 12:03 UTC, podlovchenko commented on src/components/buttons/button-submit/button-submit.js
> +let compiled = Handlebars.precompile(template);
Не увидела, где используется эта переменная

2022-07-24 12:03 UTC, podlovchenko commented on src/components/forms/form-forgotpass/form-forgotpass.hbs
> +    <div class="row" style="width: 80%; margin: 20px 0;">
Не стоит использовать инлайн стили и классы одновременно, это затрудняет поддержку и чтение кода

2022-07-24 12:03 UTC, podlovchenko commented on src/style.css.map
> +{"version":3,"sourceRoot":"","sources":["style.scss"],"names":[],"mappings":"AAQA;EACI;EACA;EAEA;EACA;EACA,OAda;;;AAkBjB;EACI;;;AAGJ;EACI;EACA;;;AAGJ;EACI;EACA;EACA;;;AAGJ;EACI;EACA;;;AAGJ;EACI;EACA;
Этого файла не должно быть в репозитории

2022-07-24 12:03 UTC, podlovchenko commented on src/style.scss
> +
Было бы здорово разбить css файл на несколько модулей, в таком большом файле сложно ориентироваться

2022-07-26 10:58 UTC, podlovchenko approved these changes
Привет, работу принимаю)

2022-07-26 10:58 UTC, podlovchenko commented on .parcelrc
> +}
Лишние строки, нет отступов

2022-07-26 10:58 UTC, podlovchenko commented on package.json
> +    "start": "node server.js --port 3000"
Ключ --port 3000 нужен к команде dev

2022-07-26 10:58 UTC, podlovchenko commented on src/components/avatars/change-avatar/index.js
> +export default (data) => {
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая [статья](https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/) на эту тему

2022-07-26 10:58 UTC, podlovchenko commented on src/components/chat-main/chat-main.scss
> +  .chat-main__message-form label {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-07-26 16:03 UTC, zayarnaya commented on .parcelrc
> +}
done

2022-07-26 16:04 UTC, zayarnaya commented on package.json
> +    "start": "node server.js --port 3000"
done

2022-07-26 16:05 UTC, zayarnaya commented on src/components/avatars/change-avatar/index.js
> +export default (data) => {
Взяла дефолтные экспорты из веба по шаблонизаторам, сама их не очень люблю )

2022-07-26 16:06 UTC, zayarnaya commented on src/components/chat-main/chat-main.scss
> +  .chat-main__message-form label {
Ок

2022-07-26 16:07 UTC, zayarnaya commented on .parcelrc
> +}
Спасибо за проверку и комментарии! (надеюсь, Вы увидите )))

2022-07-26 16:51 UTC, merged